class Product {
    id: number
    ref_number: string
    customer_ref_number: string
    showroom_id: null
    country_of_origin: string
    title: string
    sub_title: string
    default_image: {}
    price: string
    recommended_retail_price: string
    article_number: string
    currency: string
    brand: object
    tags: object
    color: object
    gender: number
    style: number
    packing_type: number
    sell_by_pairs: boolean
    min_size_eu: number
    max_size_eu: number
    is_actual: boolean
    is_archived: boolean
    is_hidden: boolean
    is_bidding_allowed: boolean
    is_collection: boolean
    collection_shipping_date: null
    has_discount: boolean
    discount_price: null
    discount_end_date: null
}
